---
################
# INSTALLATION #
################

- name: Install AWX
  package:
    name:
    - awx
    state: present
  register: installed_awx
  until: installed_awx is succeeded

#################
# CONFIGURATION #
#################
#- name: Initial configuration of AWX - create superuser
#  shell: |
#    set -o pipefail
#    echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')" | \
#    scl enable rh-python36 rh-postgresql10 "awx-manage shell"
#  become: true
#  become_user: awx
#  register: awx_create_superuser_output
#  ignore_errors: true
#  when: true
#  args:
#    executable: /bin/sh

- name: Import Database data
  command: /opt/awx/bin/awx-manage migrate
  become: true
  become_user: awx
  when: true
  changed_when: false

- name: Configure shell for AWX user
  user:
    name: awx
    shell: /bin/bash
  become: true
  become_user: root

- name: Initial configuration of AWX - create superuser
  shell: |
    set -o pipefail
    echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')" | \
    /opt/awx/bin/awx-manage shell
  args:
    executable: /bin/bash
  become: true
  become_user: awx
  when: true
  changed_when: false

- name: Initial configuration of AWX - create preload data
  command: /opt/awx/bin/awx-manage create_preload_data
  become: true
  become_user: awx
  when: true
  changed_when: false

- name: Initial configuration of AWX - provision instance
  command: /opt/awx/bin/awx-manage provision_instance --hostname=$(hostname)
  become: true
  become_user: awx
  when: true
  changed_when: false

- name: Initial configuration of AWX - register queue
  command: /opt/awx/bin/awx-manage register_queue --queuename=tower --hostnames=$(hostname)
  become: true
  become_user: awx
  when: true
  changed_when: false


# Start and enable SYSTEMD services

- name: Start and enable AWX service - cbreceiver
  systemd:
    enabled: true
    state: started
    name: awx-cbreceiver
  become: true
  become_user: root

- name: Start and enable AWX service - dispatcher
  systemd:
    enabled: true
    state: started
    name: awx-dispatcher
  become: true
  become_user: root

- name: Start and enable AWX service - channels-worker
  systemd:
    enabled: true
    state: started
    name: awx-channels-worker
  become: true
  become_user: root

- name: Start and enable AWX service - daphne
  systemd:
    enabled: true
    state: started
    name: awx-daphne
  become: true
  become_user: root

- name: Start and enable AWX service - web
  systemd:
    enabled: true
    state: started
    name: awx-web
  become: true
  become_user: root
