---
################
# INSTALLATION #
################

- name: Install AWX
  package:
    name:
    - awx
    state: present
  register: installed_awx
  until: installed_awx is succeeded

#################
# CONFIGURATION #
#################

- name: Import Database data
  command: /opt/awx/bin/awx-manage migrate
  become: true
  become_user: awx
  when: true
  changed_when: false

- name: Configure shell for AWX user
  user:
    name: awx
    shell: /bin/bash

- name: Initial configuration of AWX - create superuser
  shell: |
    set -o pipefail
    echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')" | \
    /opt/awx/bin/awx-manage shell
  args:
    executable: /bin/bash
  ignore_errors: true
  #
  #django_manage:
  #  command:
  #    "createsuperuser --noinput --username=admin --email=admin@example.com"
  #  app_path: /opt/awx
  become: true
  become_user: awx
  when: true
  changed_when: false

- name: Initial configuration of AWX - create preload data
  command: /opt/awx/bin/awx-manage create_preload_data
  become: true
  become_user: awx
  when: true
  changed_when: false

- name: Initial configuration of AWX - provision instance
  command: /opt/awx/bin/awx-manage provision_instance --hostname=$(hostname)
  become: true
  become_user: awx
  when: true
  changed_when: false

- name: Initial configuration of AWX - register queue
  command: /opt/awx/bin/awx-manage register_queue --queuename=tower --hostnames=$(hostname)
  become: true
  become_user: awx
  when: true
  changed_when: false

# Start and enable SYSTEMD services
- name: Start and enable AWX service - cbreceiver
  systemd:
    enabled: true
    state: started
    name: awx-cbreceiver

- name: Start and enable AWX service - dispatcher
  systemd:
    enabled: true
    state: started
    name: awx-dispatcher

- name: Start and enable AWX service - channels-worker
  systemd:
    enabled: true
    state: started
    name: awx-channels-worker

- name: Start and enable AWX service - daphne
  systemd:
    enabled: true
    state: started
    name: awx-daphne

- name: Start and enable AWX service - web
  systemd:
    enabled: true
    state: started
    name: awx-web
