---
- name: Promote privileges to root
  block:
################
# INSTALLATION #
################
  - name: Install PostgreSQL and Memcached
    package:
      name:
        #- postgresql-server
        #- postgresql-contrib
        #- rh-postgresql10
        - postgresql10-server
        - postgresql10
        - memcached
        #- postgresql-libs
      state: present
    register: installed_postgres
    until: installed_postgres is succeeded

  #################
  # CONFIGURATION #
  #################
  - name: Check if PostgreSQL database is initialized.
    stat:
      path: "/var/lib/pgsql/10/data/PG_VERSION"
    register: pgdata_file

    # CONFIGURE AWX
  - name: Initialize DB
    command: /usr/pgsql-10/bin/postgresql-10-setup initdb
    when: not pgdata_file.stat.exists

  - name: Start and enable Postgresql Database services
    systemd:
      enabled: true
      state: started
      name: postgresql-10

  ### Configuring DB, Users, Permissions
  - name: Create Postgres DB
    postgresql_db:
      name: awx
      login_unix_socket: /run/postgresql
    become: true
    become_user: postgres

  - name: Create Postgres user
    postgresql_user:
      name: awx
      db: awx
      encrypted: true
      login_unix_socket: /run/postgresql
    become: true
    become_user: postgres

  become: true
