---
# CONFIGURE AWX
- name: Initialize DB
  command:
    argv:
    - scl
    - enable
    - rh-postgresql10
    - "postgresql-setup initdb"
  when: true

- name: Start and enable Postgresql Database services
  systemd:
    enable: true
    state: started
    name: rh-postgresql10-postgresql

- name: Start and enable RabbitMQ service
  systemd:
    enable: true
    state: started
    name: rabbitmq-server

- name: Create Postgres user and DB - create user
  command:
    argv:
    - scl
    - enable
    - rh-postgresql10
    - "su postgres -c \"createuser -S awx\""
  when: true

- name: Create Postgres user and DB - create DB
  command:
    argv:
    - scl
    - enable
    - rh-postgresql10
    - "su postgres -c \"createdb -O awx awx\""
  when: true

- name: Import Database data
  command:
    argv:
    - scl
    - enable
    - rh-python36
    - rh-postgresql10
    - "awx-manage migrate"
  become: true
  become_user: awx
  when: true

- name: Initial configuration of AWX
  command: |
    - echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'root@localhost', 'password')" | \
    scl enable rh-python36 rh-postgresql10 "awx-manage shell"
  become: true
  become_user: awx
  when: true

- name: Initial configuration of AWX - create preload data
  command:
    - scl
    - enable
    - rh-python36
    - rh-postgresql10
    - "awx-manage create_preload_data"
  become: true
  become_user: awx
  when: true

- name: Initial configuration of AWX - provision instance
  command:
    - scl
    - enable
    - rh-python36
    - rh-postgresql10
    - "awx-manage provision_instance --hostname=$(hostname)"
  become: true
  become_user: awx
  when: true

- name: Initial configuration of AWX - register queue
  command:
    - scl
    - enable
    - rh-python36
    - rh-postgresql10
    - "awx-manage register_queue --queuename=tower --hostnames=$(hostname)"
  become: true
  become_user: awx
  when: true

- name: Start and enable AWX service
  systemd:
    enable: true
    state: started
    name: awx
