---
- name: Get OS details
  hosts: localhost
  gather_facts: no

  tasks:

  # INSTALL AWX
  - name: add testing container to inventory
    add_host:
      name: centos-test
      ansible_connection: docker
    changed_when: false

  - name: Creates yum.repos.d directory
    delegate_to: centos-test
    file:
      path: /etc/yum.repos.d
      state: directory


  - name: Install AWX repo
    delegate_to: centos-test
    get_url:
      url: https://copr.fedorainfracloud.org/coprs/mrmeee/ansible-awx/repo/epel-7/mrmeee-ansible-awx-epel-7.repo
      dest: /etc/yum.repos.d/mrmeee-ansible-awx-epel-7.repo

  - name: Install EPEL Release
    delegate_to: centos-test
    package:
      name:
      - epel-release
      state: latest

  - name: Install SCL
    delegate_to: centos-test
    package:
      name:
      - centos-release-scl
      - scl-utils-build
      state: latest

  - name: Install RabbitMQ
    delegate_to: centos-test
    package:
      name: rabbitmq-server
      state: latest

  - name: Install Postgres and Memcached
    delegate_to: centos-test
    package:
      name: 
        - rh-postgresql10
        - memcached
      state: latest

  - name: Install Python dependancies
    delegate_to: centos-test
    package:
      name: 
        - rh-python36
        - memcached
      state: latest

  - name: Install other Python dependancies
    delegate_to: centos-test
    yum:
      name: 
        - 'rh-python36*'
      disablerepo:
      - '*'
      enablerepo: 
      - mrmeee-ansible-awx
      - base
      exclude:
      - '*-debuginfo'
      state: latest

  - name: Install AWX
    delegate_to: centos-test
    yum:
      name:
      - ansible-awx
      state: latest