---
- name: Creates yum.repos.d directory
  file:
    path: /etc/yum.repos.d
    state: directory
    mode: 0644


- name: Install AWX repo
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/mrmeee/ansible-awx/repo/epel-7/mrmeee-ansible-awx-epel-7.repo
    dest: /etc/yum.repos.d/mrmeee-ansible-awx-epel-7.repo

- name: Install EPEL Release
  package:
    name:
    - epel-release
    state: present
  register: installed_epel_release
  until: installed_epel_release is succeeded

- name: Install SCL
  package:
    name:
    - centos-release-scl
    - scl-utils-build
    state: present
  register: installed_scl
  until: installed_scl is succeeded

- name: Install RabbitMQ
  package:
    name: rabbitmq-server
    state: present
  register: installed_rabbit_mq
  until: installed_rabbit_mq is succeeded

- name: Install Postgres and Memcached
  package:
    name:
      - rh-postgresql10
      - memcached
    state: present
  register: installed_postgres
  until: installed_postgres is succeeded

- name: Install Python dependancies
  package:
    name:
      - rh-python36
    state: present
  register: installed_python_dependancies
  until: installed_python_dependancies is succeeded

- name: Install other Python dependancies
  yum:
    name:
      - 'rh-python36*'
    disablerepo:
    - '*'
    enablerepo:
    - mrmeee-ansible-awx
    - base
    exclude:
    - '*-debuginfo'
    state: present
  register: installed_python36
  until: installed_python36 is succeeded

- name: Install AWX
  yum:
    name:
    - ansible-awx
    state: present
  register: installed_awx
  until: installed_awx is succeeded
