---
- block:

  - name: Create /etc/yum.repos.d directory
    file:
      path: /etc/yum.repos.d
      state: directory
      mode: 0644

  - name: Add AWX repository
    get_url:
      url: https://copr.fedorainfracloud.org/coprs/mrmeee/ansible-awx/repo/epel-7/mrmeee-ansible-awx-epel-7.repo
      dest: /etc/yum.repos.d/mrmeee-ansible-awx-epel-7.repo

  - name: Add EPEL, SCL repositories
    package:
      name:
      - epel-release
      - centos-release-scl
      - centos-release-scl-rh
      state: present
    register: installed_epel_release
    until: installed_epel_release is succeeded

  become: true
  become_user: root
